### ISSUE TITLE
Intermediate migrations don't get applied

### ISSUE THREAD

**Issue by etaroza** [sensedeep/onetable-migrate#7]
If I run the `migrate.apply(+1, '0.0.3')` on the empty database, I have only one migration in the db

After I apply one by one 0.0.1 then 0.0.2 then 0.0.3, and then run `migrate.apply(-1, '0.0.1')` it simply removes the 0.0.1 migration from the db.

In the documentation it says that all intermediate migrations will be applied when upgrading/downgrading. So I guess it's a bug?

**Comment by etaroza** [comment]
Another problem, when I run `migrate.apply(0, 'latest')` it will run only 3 migrations like this:

- `0.0.1` run correctly
- `0.0.2` run correctly
- `0.0.3` not run
- `latest` run correctly, but the migration in the db is marked as 0.0.3, I would expect that it would be marked as `0.0.4`

**Comment by mobsense** [comment]
Dealing with the first issue first:

apply up and down are only running one migration and are not applying intermediate migrations. This is a bug. It should apply all intermediate migrations. However, down migrations ARE removing the named migration which may not be the most recent migration. This is also a bug.

The latest migration is special. It does NOT run the intermediate migrations but does create their entries in the table. i.e. the latest migration is a single migration that once applied, should be equivalent to all the prior migrations. After applying the latest migration, you should be able to downgrade progressively through all migrations.

**Comment by etaroza** [comment]
Any hope that you'll be fixing it eventually?

**Comment by mobsense** [comment]
We aim to fix all issues and sooner rather than later. We've got some other changes pending too like "named migrations" to perform regular maintenance tasks.

**Comment by mobsense** [comment]
Working on this issue now. Expect to land next week.

**Comment by mobsense** [comment]
We're about to post an update that supports named migrations and wanted to ensure this issue was fully addressed.

In the new release, you can have versioned migrations that are stepped through sequentially and you can have any number of named migrations. Named migrations are for specific tasks, maintenance routines or special migrations. The "latest" migration is called "reset" and is a named migration.

In the current (old) version, the 'latest' migration is an example of a named migration. It was invoked when you did a apply(0).  In SenseDeep, this was invoked when you clicked "Reset" -- I know this is confusing, so we are cleaning this up. A reset (or latest migration) is an example of a named migration that does a particular set of database mutations.

So you have versioned migrations and named migrations. The apply API is generalized to support this, but in a backward compatible manner.

Previously it was 

    apply(direction, version)

Now (or in the next release):

```
async apply(action, version, options = {})
```

The action can be "up", "down", "repeat" or any named migration. The version is only considered for up and down.

If you go "up" to a version, all intermediate versions will be run (but not any named migrations). If you go "down", all intermediate versions will be run (but not any applied named migrations).

To be clear:
* When the "latest" or "reset" migration is run, only the "reset" migration script is run. And the version will be set to the highest versioned migration. Note: migration versions are not run, but they will be entered into the migration table so you can step "down" after doing a "reset".

**Comment by mobsense** [comment]
Should be fixed in new release.
